

FROM alpine:3.23.4

WORKDIR /app/

RUN apk --no-cache add nginx

USER nginx

COPY --chown=nginx:nginx ./nginx/conf/nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx ./nginx/lib/ /usr/share/nginx/lib/
COPY --chown=nginx:nginx ./nginx/html/ /usr/share/nginx/html/

CMD [ "/usr/sbin/nginx", "-g", "daemon off;" ]