

FROM alpine:3.23.4


RUN apk --no-cache add nginx nodejs npm

USER nginx
WORKDIR /app/

COPY --chown=nginx:nginx ./frontend/ /data/www/
RUN cd /data/www && npm install && npm run build

COPY --chown=nginx:nginx ./nginx/conf/nginx.conf /etc/nginx/nginx.conf

CMD [ "/usr/sbin/nginx", "-g", "daemon off;" ]